const jobs = [
  {
    title: "Assistant Superintendent",
    course: "Goshen Golf Club",
    location: "Augusta, Georgia",
    housing: "Housing Unknown",
    pay: "Not listed",
    applyText: "Visit Employer",
    applyLink: "https://www.goshengolfclub.com/",
    contact: "706-793-1035",
    description:
      "Assistant Superintendent position supporting golf course maintenance operations, turf health, irrigation, fertilizer and pesticide programs, staff supervision, course setup, and record keeping.",
  },
  {
    title: "Line Cook",
    course: "Sagebrush Golf Club",
    location: "Merritt, BC",
    housing: "No Housing",
    pay: "Not listed",
    applyText: "Visit Employer",
    applyLink: "https://sagebrushgolfclub.com/contact-us/",
    contact: "Contact employer",
    courseRating: 4.7,
    difficulty: "Hard",
    staffRating: 4.2,
    description: "Kitchen position at Sagebrush Golf Club.",
  },
  {
    title: "Grounds Crew",
    course: "Fairmont Hot Springs Resort",
    location: "Fairmont Hot Springs, BC",
    housing: "Housing Available",
    pay: "Not listed",
    applyText: "Visit Employer",
    applyLink: "https://www.fairmonthotsprings.com/careers",
    contact: "Contact employer",
    description: "Grounds crew position with housing available.",
  },
  {
    title: "Guest Services",
    course: "Big Sky Golf Club",
    location: "Pemberton, BC",
    housing: "Partial Housing",
    pay: "Not listed",
    applyText: "Visit Employer",
    applyLink: "https://bigskygolf.ca/contact-us/",
    contact: "Contact employer",
    courseRating: 4.6,
    difficulty: "Moderate",
    staffRating: 4.0,
    description: "Guest services position with partial housing.",
  },
  {
    title: "Maintenance",
    course: "Sandpiper Golf Course",
    location: "Harrison Mills, BC",
    housing: "No Housing",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://www.sandpipergolf.com",
    contact: "Contact employer",
    courseRating: 4.3,
    difficulty: "Moderate",
    staffRating: 3.9,
    description: "Seasonal maintenance role at a scenic Fraser Valley course.",
  },
  {
    title: "Resort Staff",
    course: "Fairmont Banff Springs",
    location: "Banff, AB",
    housing: "Housing Available",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://careers.accor.com",
    contact: "Contact employer",
    courseRating: 4.8,
    difficulty: "Hard",
    staffRating: 4.5,
    description: "Luxury resort golf environment with staff housing.",
  },
  {
    title: "Guest Services",
    course: "Whistler Golf Club",
    location: "Whistler, BC",
    housing: "Partial Housing",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://www.whistlergolf.com",
    contact: "Contact employer",
    courseRating: 4.4,
    difficulty: "Moderate",
    staffRating: 4.0,
    description: "Guest services role at a high traffic Whistler course.",
  },
  {
    title: "Resort Operations",
    course: "Predator Ridge",
    location: "Vernon, BC",
    housing: "Housing Available",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://www.predatorridge.com",
    contact: "Contact employer",
    courseRating: 4.6,
    difficulty: "Moderate-Hard",
    staffRating: 4.3,
    description: "Seasonal resort operations role at an Okanagan golf property.",
  },
  {
    title: "Course Staff",
    course: "Nicklaus North",
    location: "Whistler, BC",
    housing: "No Housing",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://nicklausnorth.com",
    contact: "Contact employer",
    courseRating: 4.5,
    difficulty: "Moderate",
    staffRating: 3.8,
    description: "Course staff role at a well-known Whistler golf course.",
  },
  {
    title: "Course / Hospitality Staff",
    course: "Tobiano Golf Course",
    location: "Kamloops, BC",
    housing: "No Housing",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://tobianogolf.com",
    contact: "Contact employer",
    courseRating: 4.8,
    difficulty: "Hard",
    staffRating: 4.3,
    description:
      "Seasonal course and hospitality work at a desert-style course overlooking Kamloops Lake.",
  },
  {
    title: "Resort Staff",
    course: "Talking Rock Golf Course",
    location: "Chase, BC",
    housing: "Partial Housing",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://qhotels.ca/talking-rock",
    contact: "Contact employer",
    courseRating: 4.6,
    difficulty: "Moderate",
    staffRating: 4.2,
    description: "Lakeside resort golf role with strong tourism traffic.",
  },
  {
    title: "Mountain Course Staff",
    course: "Greywolf Golf Course",
    location: "Panorama, BC",
    housing: "Housing Available",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://greywolfgolf.com",
    contact: "Contact employer",
    courseRating: 4.7,
    difficulty: "Hard",
    staffRating: 4.4,
    description: "Mountain course staff role at Greywolf Golf Course.",
  },
  {
    title: "Resort / Course Staff",
    course: "Sun Peaks Golf Course",
    location: "Sun Peaks, BC",
    housing: "Partial Housing",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://sunpeaksresort.com",
    contact: "Contact employer",
    courseRating: 4.5,
    difficulty: "Moderate",
    staffRating: 4.1,
    description:
      "Seasonal resort and course staff role in a busy resort environment.",
  },
  {
    title: "Course / Clubhouse Staff",
    course: "The Rise Golf Course",
    location: "Vernon, BC",
    housing: "No Housing",
    pay: "Contact employer",
    applyText: "Visit Employer",
    applyLink: "https://therisegolf.ca",
    contact: "Contact employer",
    courseRating: 4.5,
    difficulty: "Moderate-Hard",
    staffRating: 4.1,
    description:
      "Course and clubhouse staff role at an elevated course with panoramic views.",
  },
];

export default jobs;
